modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/FTBTeam/FTB-Dripper/issues"
license = "All Rights Reserved"

[[mods]]
modId = "ftbdripper"
version = "${version}"
displayName = "FTB Dripper"
authors = "FTB Team"
description = '''
Adds Dripper. Nothing else.
'''

[[dependencies.ftbdripper]]
modId = "forge"
mandatory = true
versionRange = "[43.2.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbdripper]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"