name: Build & Release

on:
  push:
    types: [ published ]

jobs:
  build:
    uses: FTBTeam/mods-meta/.github/workflows/standard-release.yml@main
    with:
      curse-publish-task: curseforge
    secrets:
      ftb-maven-token: ${{ secrets.FTB_MAVEN_TOKEN }}
      curse-token: ${{ secrets.CURSEFORGE_KEY }}